defmodule ExCellerate.RegistryTest do
  # Characterization tests for the macro-generated registry API. The behaviour
  # already exists, so these pass on first run — they pin the contract of the
  # code generated by `use ExCellerate.Registry` so future macro changes can't
  # silently break plugin resolution, default fallback, override, or config.
  use ExUnit.Case, async: true

  defmodule Greet do
    @moduledoc false
    @behaviour ExCellerate.Function
    def name, do: "greet"
    def arity, do: 1
    def call([name]), do: "Hello, #{name}!"
  end

  defmodule MyAbs do
    @moduledoc false
    @behaviour ExCellerate.Function
    def name, do: "abs"
    def arity, do: 1
    def call([_]), do: :overridden
  end

  defmodule Registry do
    @moduledoc false
    use ExCellerate.Registry, plugins: [Greet, MyAbs], cache_limit: 25
  end

  describe "generated resolve_function/1" do
    test "resolves a plugin function to its module" do
      assert Registry.resolve_function("greet") == {:ok, Greet}
    end

    test "resolves a built-in default that no plugin shadows" do
      assert Registry.resolve_function("sum") == {:ok, ExCellerate.Functions.Math.Sum}
    end

    test "a plugin overrides a built-in default with the same name" do
      assert Registry.resolve_function("abs") == {:ok, MyAbs}
    end

    test "returns :error for an unknown function name" do
      assert Registry.resolve_function("does_not_exist") == :error
    end
  end

  describe "generated __excellerate_config__/1" do
    test "reports the configured cache options" do
      assert Registry.__excellerate_config__(:cache_limit) == 25
      assert Registry.__excellerate_config__(:cache_enabled) == true
    end
  end

  describe "generated list_functions/0" do
    test "includes plugins alongside the built-in defaults" do
      functions = Registry.list_functions()
      assert Greet in functions
      # The override is present and the shadowed default is not duplicated.
      assert MyAbs in functions
      refute ExCellerate.Functions.Math.Abs in functions
    end
  end

  describe "end-to-end evaluation through the registry helpers" do
    test "eval!/2 calls a custom plugin function" do
      assert Registry.eval!("greet('World')") == "Hello, World!"
    end

    test "the plugin override takes effect at evaluation" do
      assert Registry.eval!("abs(-5)") == :overridden
    end

    test "built-in defaults remain callable" do
      assert Registry.eval!("sum(1, 2, 3)") == 6
    end

    test "eval/2 returns an error tuple for an unknown function" do
      assert {:error, %ExCellerate.Error{}} = Registry.eval("nope(1)")
    end
  end
end
